let i = 0;
export const data = [
  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },
  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },
  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },

  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },
  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },
  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },
  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },
  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },
  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },
  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },
  {
    id: i++,
    order: 20,
    customerName: 'Umarali',
    totalAmount: "0 so'm",
    discount: "0 so'm",
    amountSold: "0 so'm",
    customerPaid: "0 so'm",
    debt: "0 so'm",
    orderTime: '24/11/2022',
  },
];
